export enum SalaryTransactionTypeEnum {
  SALARY = "SALARY",
  ALLOWANCE = "ALLOWANCE",
  SALARY_ADVANCE = "SALARY_ADVANCE",
  ALLOWANCE_ADVANCE = "ALLOWANCE_ADVANCE",
  SALARY_DEDUCTION = "SALARY_DEDUCTION",
  ALLOWANCE_DEDUCTION = "ALLOWANCE_DEDUCTION",
}
