export enum UserRoleEnum {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  SUPERVISOR = "SUPERVISOR",
  DRIVER = "DRIVER",
  VENDOR = "VENDOR",
  FH_MANAGER = "FH_MANAGER",
  FH_SECURITY = "FH_SECURITY",
  FH_VENDOR = "FH_VENDOR",
}
